title: Alexis TOUMI
description: personal website
url: https://alexis.toumi.xyz
favicon: assets/images/favicon.jpeg

safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
